### ISSUE TITLE
Multi-options

### ISSUE THREAD

**Issue by CarlosAp01** [go-telegram/ui#5]
Hello ,

I have applied several of the examples in this framwork and it has worked correctly. Now I have a doubt, is it possible to select several inline buttons? if I have for example: 4 inline buttons in a chat, and I want to select 2 or more of those buttons and then press a 5th button to accept the options I select, is this possible with inline buttons?

Thank you very much in advance

**Comment by negasus** [comment]
You can't use UI library for this, but you can do it with main library, see an example
https://github.com/go-telegram/bot/tree/main/examples/inline_keyboard_multiselect
